--QUESTION 1
CREATE TABLE VILLE(
    ID_VILLE VARCHAR2 PRIMARY KEY,
    XMIN INTEGER NOT NULL,
    XMAX INTEGER NOT NULL,
    YMIN INTEGER NOT NULL,
    YMAX INTEGER NOT NULL
);
CREATE TABLE PILOTE(
    PLNUM INTEGER PRIMARY KEY,
    PLNOM VARCHAR2(50) NOT NULL,
    PLPRENOM VARCHAR2(50) NOT NULL,
    SALAIRE INTEGER NOT NULL,
    ID_VILLE INTEGER NOT NULL,
    FOREIGN KEY (ID_VILLE) REFERENCES VILLE(ID_VILLE)
);
CREATE TABLE AVION(
    AV_NUM INTEGER PRIMARY KEY,
    AVNOM VARCHAR2(50) NOT NULL,
    LOCALISATION VARCHAR2(50) NOT NULL,
    CAPACITE INTEGER NOT NULL,
    FOREIGN KEY (LOCALISATION) REFERENCES VILLE(ID_VILLE)
);
CREATE TABLE AGENCE(
    CODE VARCHAR2 PRIMARY KEY,
    VILLE VARCHAR2 NOT NULL,
    FOREIGN KEY (VILLE) REFERENCES VILLE(ID_VILLE)
)
CREATE TABLE VOL2(
    VOLNUM INTEGER PRIMARY KEY,
    PLNUM INTEGER NOT NULL,
    AV_NUM INTEGER NOT NULL,
    VILLEDEP VARCHAR2(50) NOT NULL,
    VILLEARR VARCHAR2(50) NOT NULL,
    HEUREDEP INTEGER NOT NULL,
    HEUREARR INTEGER NOT NULL,
    FOREIGN KEY (PLNUM) REFERENCES PILOTE(PLNUM),
    FOREIGN KEY (AV_NUM) REFERENCES AVION(AV_NUM),
    FOREIGN KEY (VILLEDEP) REFERENCES VILLE(ID_VILLE),
    FOREIGN KEY (VILLEARR) REFERENCES VILLE(ID_VILLE)
);
-- QUESTION 2
INSERT ALL
  INTO VILLE (ID_VILLE, XMIN, XMAX, YMIN, YMAX) VALUES ('Dijon', 8950, 9180, 4840, 5050) 
  INTO VILLE (ID_VILLE, XMIN, XMAX, YMIN, YMAX) VALUES ('Lyon', 8820, 9080, 7020, 7230)
  INTO VILLE (ID_VILLE, XMIN, XMAX, YMIN, YMAX) VALUES ('Paris', 6310, 6560, 2940, 3110)
  INTO VILLE (ID_VILLE, XMIN, XMAX, YMIN, YMAX) VALUES ('Marseille', 9660, 9930, 10350, 10580)
  INTO VILLE (ID_VILLE, XMIN, XMAX, YMIN, YMAX) VALUES ('Nantes', 2730, 2970, 5320, 5540)
SELECT 1 FROM dual;

INSERT ALL
  INTO PILOTE (PLNUM, PLNOM, PLPRENOM, SALAIRE, ID_VILLE) VALUES (4, 'Dupont', 'Nicolas', 17000, 'Paris')
SELECT 1 FROM dual;

INSERT ALL
  INTO AVION (AV_NUM, AVNOM, LOCALISATION, CAPACITE) VALUES (3, 'B707', 'Paris', 250)
  INTO AVION (AV_NUM, AVNOM, LOCALISATION, CAPACITE) VALUES (4, 'A300', 'Lyon', 280)
SELECT 1 FROM dual;

INSERT ALL
INTO AGENCE (CODE, VILLE)VALUES('AG001', 'Paris')
INTO AGENCE (CODE, VILLE)VALUES('AG004', 'Lyon')
SELECT 1 FROM dual;

INSERT ALL 
INTO VOL2 (VOLNUM, PLNUM, AV_NUM, VILLEDEP, VILLEARR, HEUREDEP, HEUREARR)VALUES (2, 1, 4, 'Paris', 'Dijon', 17, 18 )
INTO VOL2 (VOLNUM, PLNUM, AV_NUM, VILLEDEP, VILLEARR, HEUREDEP, HEUREARR)VALUES (5, 4, 3, 'Paris', 'Marseille', 06, 08)
SELECT 1 FROM dual;


--QUESTION 3
RENAME  VOL2 TO TRAJETS;
RENAME  PILOTE TO PERSONNEL;

--QUESTION 4
UPDATE TRAJETS SET HEUREARR = 17 WHERE VOLNUM = 5;
UPDATE TRAJETS SET VILLEARR = 'Lyon' WHERE VOLNUM = 5;

--QUESTION 5 
DELETE FROM TRAJETS WHERE VOLNUM = 5;

--QUESTION 6

ALTER TABLE PERSONNEL
ADD FONCTION VARCHAR(50) DEFAULT 'pilote';

UPDATE PERSONNEL
SET FONCTION = 'pilote';

--PARTIE 2

--QUESTION 1
DESCRIBE TRAJETS;

--QUESTION 2
SELECT * FROM TRAJETS;

--QUESTION 3
SELECT PLNOM AS Nom, PLPRENOM AS Prenom, SALAIRE AS Salaire FROM PERSONNEL
ORDER BY Nom, Prenom;

--QUESTION 4
SELECT PLNOM AS Nom, PLPRENOM AS Prenom, SALAIRE AS Salaire FROM PERSONNEL
WHERE SALAIRE > 20000;

--QUESTION 5
SELECT PLNOM AS Nom, PLPRENOM AS Prenom, SALAIRE AS Salaire FROM PERSONNEL
WHERE SALAIRE = ANY(10000, 20000);

--QUESTION 6
SELECT PLNOM AS Nom, PLPRENOM AS Prenom, SALAIRE AS Salaire FROM PERSONNEL
WHERE Salaire > (SELECT AVG(SALAIRE) FROM PERSONNEL);

--QUESTION 7
SELECT AV_NUM, AVNOM FROM AVION
WHERE LOCALISATION = 'Paris';

--QUESTION 8
SELECT PLNOM AS Nom, PLPRENOM AS Prenom, SALAIRE AS Salaire FROM PERSONNEL
WHERE SALAIRE > &valeur_à_saisir;

--QUESTION 9
SELECT AV_NUM, AVNOM, CAPACITE, LOCALISATION FROM AVION
WHERE LOCALISATION = (SELECT PLNOM FROM PERSONNEL WHERE PLNUM = &valeur_à_saisir);

--QUESTION 10
SELECT VOLNUM, VILLEDEP, VILLEARR, HEUREDEP, HEUREARR, AVNOM, PLNOM FROM TRAJETS T
JOIN PERSONNEL P
ON P.PLNUM = T.PLNUM
JOIN AVION A
ON A.AV_NUM =T.AV_NUM
WHERE VOLNUM = &valeur_a_saisir;